name: PHP Static Lint

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: none

      - name: Show PHP version
        run: php -v

      - name: Lint all PHP files
        run: |
          set -e
          if git ls-files '*.php' | grep -q .; then
            git ls-files '*.php' | xargs -I{} -P 4 php -l {}
          else
            echo "No PHP files found."
          fi
